import '@angular/material';
import '@angular/platform-browser';
import '@angular/platform-browser-dynamic';
import '@angular/core';
import '@angular/common';
import '@angular/http';
import '@angular/router';
import '@angular/forms'
import '@angular/material'
import 'hammerjs'
import 'socket.io-client';
import 'angular-esri-loader'
import 'rxjs/Observable'
import 'rxjs/Subject'
import 'rxjs/add/operator/map'
import 'rxjs/add/operator/catch'
import 'rxjs/add/observable/of'
import 'rxjs/add/observable/throw'
import { MatSnackBar, MatSnackBarConfig, MatSnackBarModule } from '@angular/material';
import '@angular/cdk'
